#!/bin/bash
export GO_HTTP_PORT='9999'
export LOG_LEVEL='INFO'
export DEPLOY_ENVIRONMENT='DEVELOP'
export REDIS_TYPE='redis_default'
export REDIS_ENDPOINT_LIST='localhost:6379,localhost:7001,localhost:7002,localhost:7003,localhost:7004,localhost:7005"'
export REDIS_PASSWORD=''
export MONGO_URI='mongodb://localhost:27017/go-base-service?rm.failover=1000ms:5x1&rm.monitorRefreshMS=100&rm.nbChannelsPerNode=1'
export POSTGRES_HOST='localhost'
export POSTGRES_PORT='5432'
export POSTGRES_USERNAME='postgres'
export POSTGRES_PASSWORD=''
export POSTGRES_NAME='postgres'
export NATS_URL='nats://127.0.0.1:4222'
export ELASTICSEARCH_INDEX_PREFIX='abc_'
export ELASTICSEARCH_URL='htt://localhost:9200'